# Generated by Django 4.2.30 on 2026-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('izoh', models.CharField(blank=True, default='', max_length=255)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
