# Generated by Django 4.2.30 on 2026-07-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tolov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranzaksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('qoshildi', "Qarzga qo'shildi"), ('tolov', "To'lov qilindi")], max_length=10)),
                ('summa', models.FloatField()),
                ('izoh', models.CharField(blank=True, default='', max_length=255)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('arxiv_mijoz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranzaksiyalar', to='api.arxivmijoz')),
                ('mijoz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranzaksiyalar', to='api.mijoz')),
            ],
        ),
        migrations.DeleteModel(
            name='Tolov',
        ),
    ]
