# Generated by Django 4.2.30 on 2026-07-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tranzaksiya_delete_tolov'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolanganArxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_summa', models.FloatField()),
                ('tranzaksiyalar_soni', models.IntegerField(default=0)),
                ('boshlanish_sana', models.DateTimeField(blank=True, null=True)),
                ('tugash_sana', models.DateTimeField(blank=True, null=True)),
                ('ochirilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('tafsilotlar', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='tranzaksiya',
            name='arxivlandi',
            field=models.BooleanField(default=False),
        ),
    ]
